# Generated by Django 4.1.1 on 2022-09-17 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_professor_professor_courseoffering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='name',
        ),
        migrations.AddField(
            model_name='professor',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='professor',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.professor'),
        ),
    ]
