# Generated by Django 4.1.1 on 2022-09-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_professor_name_professor_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='abbreviation',
            field=models.CharField(default=models.CharField(max_length=50), max_length=50),
        ),
    ]
