# Generated by Django 4.1.1 on 2022-09-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_lecture_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
