# Generated by Django 4.1.1 on 2022-09-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_lecture_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
